version: '2'

services:
  web:
    build: .
    command: python manage.py migrate --noinput
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/project
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: