version: '2'

services:
  nginx:
    image: nginx:alpine
    container_name: tiamat_nginx
    ports:
      - "8000:8000"
    volumes:
      - .:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web

  web:
    build:
      context: .
      args:
        requirements: requirements/dev.txt
    container_name: tiamat_web
    command:
      - /bin/sh
      - -c
      - |
        ./manage.py makemigrations
        ./manage.py migrate --noinput
        ./manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/project
    expose:
      - "8000"
    environment:
      - DJANGO_SETTINGS_MODULE=tiamat_head.settings.development
    depends_on:
      - postgres

  postgres:
    image: postgres:10.1-alpine
    container_name: tiamat_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: